I terminus
bugout-dev/dao pull request #53
Opened 2022-07-04 11:30 UTC by peersky

## Changes

## How to test these changes?

## Related issues
#13

2022-07-04 16:44 UTC, peersky commented
```
cd build/contracts
diff  <(jq --sort-keys .abi TerminusFacet.json) <(jq --sort-keys .abi ITerminus.json)        
3,7d2
<     "inputs": [],
<     "stateMutability": "nonpayable",
<     "type": "constructor"
<   },
<   {
743c738
<         "name": "poolID",
---
>         "name": "id",
(.dao) t@Peersky-mb contracts % diff  <(jq --sort-keys .abi ERC1155WithTerminusStorage.json) <(jq --sort-keys .abi IERC1155WithTerminusStorage.json) 
3,7d2
<     "inputs": [],
<     "stateMutability": "nonpayable",
<     "type": "constructor"
<   },
<   {
346c341
<         "name": "poolID",
---
>         "name": "id",
```

2022-07-06 17:50 UTC, zomglings requested changes
Terminus interface has changed in the most recent releases. This needs to be updated.

Given that Terminus is still in flux, I would rather do this kind of work using codegen than manually maintaining `ITerminus.sol`. @peersky : Do you want to build the code generator?

It would also be nice to have a tool which could test an interface against an actual ABI to make sure that the interface is complete (or as complete as it needs to be).

2022-07-06 17:50 UTC, zomglings commented on contracts/interfaces/ITerminus.sol
> +interface ITerminus is IERC1155WithTerminusStorage {
I would rather this was codegen'd instead of created manually.

2022-07-06 17:51 UTC, zomglings commented
Tests are passing on my machine.

2022-07-07 10:32 UTC, peersky commented
@zomglings there already is hh plugin that does such generation: https://github.com/dmihal/hardhat-interface-generator if we plan to migrate to hardhat than we can use it, otherwise script is quite simple to reapply to our realities

Nevertheless, in current PR there are points where source code has to be modified anyway so purely generating interface file is not enough.

2022-10-31 09:55 UTC, zomglings commented
Stale.

2022-10-31 09:55 UTC, closed without merging